/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Telefone;

/**
 *
 * @author pedro
 */
public class AdicionarTelefoneView extends javax.swing.JFrame {

    
    private HomeAloneView homeAloneView;
    /**
     * Creates new form AdicionarTelefoneView
     */
    public AdicionarTelefoneView(HomeAloneView homeAloneView) {
        this.homeAloneView = homeAloneView;
        this.homeAloneView.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        tfDdd = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        jlVoltar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cadastrar Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DDD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telefone:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        tfTelefone.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfTelefone.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 350, 40));

        tfDdd.setBackground(new java.awt.Color(255, 255, 255));
        tfDdd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfDdd.setForeground(new java.awt.Color(0, 0, 0));
        tfDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDddActionPerformed(evt);
            }
        });
        getContentPane().add(tfDdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 150, 40));

        btSalvar.setBackground(new java.awt.Color(95, 46, 234));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 487, 45));

        jlVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jlVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jlVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 46, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDddActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String ddd = tfDdd.getText();
        String telefone = tfTelefone.getText();
        ArrayList<Telefone> telefones = homeAloneView.getTelefones();
        boolean existe = false;
        
        for (Telefone telefoneFor : telefones) {
            if (telefoneFor.getDdd().equals(ddd) 
                && telefoneFor.getTelefone().equals(telefone)){
                existe = true;
                break;
            }
        }
        if (existe){
            JOptionPane.showMessageDialog(null, "Telefone já cadastrado");
        } else {
            telefones.add(new Telefone(ddd, telefone));
            JOptionPane.showMessageDialog(null, "Telefone cadastrado com sucesso!");
        }
        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void jlVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVoltarMouseClicked
        this.dispose();
        this.homeAloneView.setVisible(true);
    }//GEN-LAST:event_jlVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JTextField tfDdd;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
