/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Endereco;

/**
 *
 * @author pedro
 */
public class AdicionarEnderecoView extends javax.swing.JFrame {
    
    private HomeAloneView homeAloneView;
    /**
     * Creates new form AlterarEnderecoView
     */
    public AdicionarEnderecoView(HomeAloneView homeAloneView) {
        this.homeAloneView = homeAloneView;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btSalvar1 = new javax.swing.JButton();
        tfLogradouro = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        tfCep = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jlVoltar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logradouro:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cidade:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CEP:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 40, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Complemento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 290, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cadastrar endereço");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 60));

        btSalvar1.setBackground(new java.awt.Color(95, 46, 234));
        btSalvar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar1.setText("Salvar");
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 470, 45));

        tfLogradouro.setBackground(new java.awt.Color(255, 255, 255));
        tfLogradouro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfLogradouro.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 370, 30));

        tfComplemento.setBackground(new java.awt.Color(255, 255, 255));
        tfComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfComplemento.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 370, 30));

        tfCep.setBackground(new java.awt.Color(255, 255, 255));
        tfCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCep.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, 30));

        tfBairro.setBackground(new java.awt.Color(255, 255, 255));
        tfBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBairro.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 30));

        tfCidade.setBackground(new java.awt.Color(255, 255, 255));
        tfCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCidade.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 220, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bairro:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 190, 60, -1));

        jlVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jlVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jlVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        ArrayList<Endereco> enderecos = homeAloneView.getEnderecos();
        String logradouro = tfLogradouro.getText();
        String cidade = tfCidade.getText();
        String bairro = tfBairro.getText();
        String cep = tfCep.getText();
        int cepInt = 0;
        try {
            cepInt = Integer.parseInt(cep);
        } catch(Exception ex){};
        String complemento = tfComplemento.getText();
        boolean existe = false;

        for (Endereco enderecoFor : enderecos) {
            if (enderecoFor.getLogradouro().equals(logradouro) 
                && enderecoFor.getCidade().equals(cidade)){
                enderecoFor.setBairro(bairro);
                enderecoFor.setCep(cepInt);
                enderecoFor.setComplemento(complemento);
                existe = true;
                break;
            }
        }
        if (existe){
            JOptionPane.showMessageDialog(null, "Endereço já cadastrado");
        } else {
            enderecos.add(new Endereco(cepInt, logradouro, complemento, bairro, cidade));
            JOptionPane.showMessageDialog(null, "Endereço cadastrado com sucesso!");
        }
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void jlVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVoltarMouseClicked
        this.dispose();
        this.homeAloneView.setVisible(true);
    }//GEN-LAST:event_jlVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfLogradouro;
    // End of variables declaration//GEN-END:variables
}
