/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Produto;
import visao.HomeAloneView;
import visao.NovoPedidoView;

/**
 *
 * @author pedro
 */
public class CadastrarProdutoView extends javax.swing.JFrame {
    private NovoPedidoView novoPedidoView;
    private HomeAloneView homeAloneView;
    /**
     * Creates new form CadastrarProdutoView
     */
    public CadastrarProdutoView(NovoPedidoView novoPedidoView, HomeAloneView homeAloneView) {
        initComponents();
        this.homeAloneView = homeAloneView;
        this.novoPedidoView = novoPedidoView;
        this.novoPedidoView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlVoltar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        tfNomeProduto = new javax.swing.JTextField();
        spQuantidade = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jlVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jlVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jlVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Novo Produto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome Produto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        btCadastrar.setBackground(new java.awt.Color(95, 46, 234));
        btCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 480, 40));

        tfNomeProduto.setBackground(new java.awt.Color(255, 255, 255));
        tfNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNomeProduto.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 380, 30));

        spQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(spQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 80, 30));

        taDescricao.setBackground(new java.awt.Color(255, 255, 255));
        taDescricao.setColumns(20);
        taDescricao.setForeground(new java.awt.Color(0, 0, 0));
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 380, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVoltarMouseClicked
        this.dispose();
        this.novoPedidoView.setVisible(true);
    }//GEN-LAST:event_jlVoltarMouseClicked

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        ArrayList<Produto> produtos = this.homeAloneView.getProdutos();
        String nomeProduto = tfNomeProduto.getText();
        String descricao = taDescricao.getText();
        Integer quantidade = (Integer) spQuantidade.getValue();
        boolean existe = false;
        
        for (Produto produto : produtos) {
            if (produto.getNome().equals(nomeProduto)){
                produto.setDescricao(descricao);
                produto.setQtdSelecionada(quantidade);
                existe = true;
                break;
            }
        }
        
        if (existe){
            JOptionPane.showMessageDialog(null, "Produto Atualizado!");
        } else {
            produtos.add(new Produto(nomeProduto, descricao, quantidade));
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
        }
        
        this.novoPedidoView.atualizaComboProdutos();
    }//GEN-LAST:event_btCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfNomeProduto;
    // End of variables declaration//GEN-END:variables
}
