/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Guilherme
 */
public class CadastroUsuarioView extends javax.swing.JFrame {
    private ArrayList<Usuario> usuarios;
    private LoginUsuarioView login;
            
    /**
     * Creates new form LoginUsuarioView
     */
    public CadastroUsuarioView(LoginUsuarioView login) {
        this.usuarios = login.getUsuarios();
        this.login = login;
        this.login.setVisible(false);
        initComponents();
    }

    CadastroUsuarioView(MouseEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCpfCnpj = new javax.swing.JTextField();
        jlVoltar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo3.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digite seu CPF/ CNPJ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        tfNome.setBackground(new java.awt.Color(255, 255, 255));
        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNome.setForeground(new java.awt.Color(0, 0, 0));
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 487, 40));

        pfSenha.setBackground(new java.awt.Color(255, 255, 255));
        pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pfSenha.setForeground(new java.awt.Color(0, 0, 0));
        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 298, 487, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        btConfirmar.setBackground(new java.awt.Color(95, 46, 234));
        btConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 355, 487, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastre-se");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Informe seu nome");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        tfCpfCnpj.setBackground(new java.awt.Color(255, 255, 255));
        tfCpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfCpfCnpj.setForeground(new java.awt.Color(0, 0, 0));
        tfCpfCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfCnpjActionPerformed(evt);
            }
        });
        getContentPane().add(tfCpfCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 487, 40));

        jlVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jlVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jlVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        String nome = tfNome.getText();
        String cpfCnpjText = tfCpfCnpj.getText();
        cpfCnpjText = cpfCnpjText.replaceAll("[^0-9]", "");
        String senha = pfSenha.getText();
        boolean isCadastrado = false;
        boolean valido = cpfCnpjText.matches("([0-9]{2}[\\.]?[0-9]{3}[\\.]?[0-9]{3}[\\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\\.]?[0-9]{3}[\\.]?[0-9]{3}[-]?[0-9]{2})");
        long cpfCnpj = 0;
        if (valido)
            cpfCnpj = Long.parseLong(cpfCnpjText);
        
        if (!(cpfCnpj > 0 && valido)) {
            JOptionPane.showMessageDialog(null, "CPF/CNPJ Inválido!");
        } else {
            for (Usuario usuario : usuarios) {
                if (cpfCnpj == usuario.getCpfCpnj()){
                    isCadastrado = true;
                    break;
                }
            }
            if (isCadastrado == false) {
                usuarios.add(new Usuario(nome, cpfCnpj, senha));
                JOptionPane.showMessageDialog(null, "Usuário inserido com sucesso!");
                this.dispose();
                this.login.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado!");
            }
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void tfCpfCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfCnpjActionPerformed

    private void jlVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVoltarMouseClicked
        this.dispose();
        this.login.setVisible(true);
    }//GEN-LAST:event_jlVoltarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfCpfCnpj;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
