/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JLabel;
import modelo.Cartao;
import modelo.Compra;
import modelo.Email;
import modelo.Endereco;
import modelo.Produto;
import modelo.Telefone;
import modelo.Usuario;

/**
 *
 * @author pedro
 */
public class HomeAloneView extends javax.swing.JFrame {
    private ArrayList<Telefone> telefones;
    private ArrayList<Endereco> enderecos;
    private ArrayList<Email> emails;
    private ArrayList<Cartao> cartoes;
    private ArrayList<Produto> produtos;
    private ArrayList<Compra> compras;
    
    public HomeAloneView(Usuario usuarioLogado) {
        this.telefones = new ArrayList<Telefone>();
        this.enderecos = new ArrayList<Endereco>();
        this.emails = new ArrayList<Email>();
        this.cartoes = new ArrayList<Cartao>();
        this.produtos = new ArrayList<Produto>();
        this.compras = new ArrayList<Compra>();
        carregaProdutosDefault();
        initComponents();
        String mensagem = String.format("Seja bem vindo! %s", usuarioLogado.getNome());
        jlMensagem.setText(mensagem);
         
        String mensagemEtapa = String.format("Para realizar um pedido siga os seguintes passos:");
        String mensagemEtapa2 = "1) Inicie realizando o cadastro dos dados pessoais;";
        String mensagemEtapa3 = String.format("2) Vá na aba pedidos e, em novo pedido, preencha os campos e cadastre os produtos desejados");
        String mensagemEtapa4 = String.format("Com isso feito seu pedido será concluído e atendido por um entregador!");
        jlMensagemEtapa.setText(mensagemEtapa);
        jlMensagemEtapa2.setText(mensagemEtapa2);
        jlMensagemEtapa3.setText(mensagemEtapa3);
        jlMensagemEtapa4.setText(mensagemEtapa4);
    }

    public ArrayList<Telefone> getTelefones() {
        return telefones;
    }

    public ArrayList<Endereco> getEnderecos() {
        return enderecos;
    }

    public ArrayList<Email> getEmails() {
        return emails;
    }

    public ArrayList<Cartao> getCartoes() {
        return cartoes;
    }
    
    public ArrayList<Produto> getProdutos() {
        return produtos;
    }
    
    public ArrayList<Compra> getCompras() {
        return compras;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMensagemEtapa4 = new javax.swing.JLabel();
        jlMensagemEtapa = new javax.swing.JLabel();
        jlMensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlMensagemEtapa2 = new javax.swing.JLabel();
        jlMensagemEtapa3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mbHomeAlone = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        miEndereco = new javax.swing.JMenuItem();
        miTelefone = new javax.swing.JMenuItem();
        miEmail = new javax.swing.JMenuItem();
        miPagamento = new javax.swing.JMenuItem();
        mnPedidos = new javax.swing.JMenu();
        miNovoPedido = new javax.swing.JMenuItem();
        miEmAndamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMensagemEtapa4.setBackground(new java.awt.Color(0, 0, 0));
        jlMensagemEtapa4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlMensagemEtapa4.setForeground(new java.awt.Color(255, 255, 255));
        jlMensagemEtapa4.setText("MensagemEtapa");
        getContentPane().add(jlMensagemEtapa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jlMensagemEtapa.setBackground(new java.awt.Color(0, 0, 0));
        jlMensagemEtapa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlMensagemEtapa.setForeground(new java.awt.Color(255, 255, 255));
        jlMensagemEtapa.setText("MensagemEtapa");
        getContentPane().add(jlMensagemEtapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jlMensagem.setBackground(new java.awt.Color(0, 0, 0));
        jlMensagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jlMensagem.setText("Mensagem");
        getContentPane().add(jlMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_letra.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jlMensagemEtapa2.setBackground(new java.awt.Color(0, 0, 0));
        jlMensagemEtapa2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlMensagemEtapa2.setForeground(new java.awt.Color(255, 255, 255));
        jlMensagemEtapa2.setText("MensagemEtapa");
        getContentPane().add(jlMensagemEtapa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jlMensagemEtapa3.setBackground(new java.awt.Color(0, 0, 0));
        jlMensagemEtapa3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlMensagemEtapa3.setForeground(new java.awt.Color(255, 255, 255));
        jlMensagemEtapa3.setText("MensagemEtapa");
        getContentPane().add(jlMensagemEtapa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 600, 330));

        mbHomeAlone.setForeground(new java.awt.Color(255, 255, 255));

        mnCadastros.setText("Cadastros");

        miEndereco.setText("Endereço");
        miEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEnderecoActionPerformed(evt);
            }
        });
        mnCadastros.add(miEndereco);

        miTelefone.setText("Telefone");
        miTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTelefoneActionPerformed(evt);
            }
        });
        mnCadastros.add(miTelefone);

        miEmail.setText("E-mail");
        miEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmailActionPerformed(evt);
            }
        });
        mnCadastros.add(miEmail);

        miPagamento.setText("Cartão");
        miPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPagamentoActionPerformed(evt);
            }
        });
        mnCadastros.add(miPagamento);

        mbHomeAlone.add(mnCadastros);

        mnPedidos.setText("Pedidos");

        miNovoPedido.setText("Novo Pedido");
        miNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoPedidoActionPerformed(evt);
            }
        });
        mnPedidos.add(miNovoPedido);

        miEmAndamento.setText("Pedidos");
        miEmAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmAndamentoActionPerformed(evt);
            }
        });
        mnPedidos.add(miEmAndamento);

        mbHomeAlone.add(mnPedidos);

        setJMenuBar(mbHomeAlone);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEnderecoActionPerformed
        AdicionarEnderecoView adcEndView = new AdicionarEnderecoView(this);
            adcEndView.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_miEnderecoActionPerformed

    private void miTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTelefoneActionPerformed
       AdicionarTelefoneView adcTelView = new AdicionarTelefoneView(this);
            adcTelView.setVisible(true); 
    }//GEN-LAST:event_miTelefoneActionPerformed

    private void miPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPagamentoActionPerformed
        AdicionarCartaoView adcCartaoView = new AdicionarCartaoView(this);
            adcCartaoView.setVisible(true); 
    }//GEN-LAST:event_miPagamentoActionPerformed

    private void miEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmailActionPerformed
            AdicionarEmailView adcEmailView = new AdicionarEmailView(this);
            adcEmailView.setVisible(true);
    }//GEN-LAST:event_miEmailActionPerformed

    private void miNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoPedidoActionPerformed
        NovoPedidoView novoPedidoView = new NovoPedidoView(this);
        novoPedidoView.setVisible(true); 
    }//GEN-LAST:event_miNovoPedidoActionPerformed

    private void miEmAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmAndamentoActionPerformed
         InfoPedidoView infoPedidoView = new InfoPedidoView(this);
         infoPedidoView.setVisible(true);
    }//GEN-LAST:event_miEmAndamentoActionPerformed

     private void carregaProdutosDefault() {
        Produto produto1 = new Produto("Miojo", "Macarrão instantâneo", 3);
        Produto produto2 = new Produto("Leite", "Leite em pó - Molico", 1);
        Produto produto3 = new Produto("Sabonete", "Sabonete - Dove ou Protex", 5);
        Produto produto4 = new Produto("Arroz", "Arroz branco - Urbano - 1KG", 1);
        Produto produto5 = new Produto("Pão de Forma", "Pão de Forma de Hoje", 1);
        this.produtos.add(produto1);
        this.produtos.add(produto2);
        this.produtos.add(produto3);
        this.produtos.add(produto4);
        this.produtos.add(produto5);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlMensagem;
    private javax.swing.JLabel jlMensagemEtapa;
    private javax.swing.JLabel jlMensagemEtapa2;
    private javax.swing.JLabel jlMensagemEtapa3;
    private javax.swing.JLabel jlMensagemEtapa4;
    private javax.swing.JMenuBar mbHomeAlone;
    private javax.swing.JMenuItem miEmAndamento;
    private javax.swing.JMenuItem miEmail;
    private javax.swing.JMenuItem miEndereco;
    private javax.swing.JMenuItem miNovoPedido;
    private javax.swing.JMenuItem miPagamento;
    private javax.swing.JMenuItem miTelefone;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnPedidos;
    // End of variables declaration//GEN-END:variables
}
