/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Produto;
import modelo.Usuario;

/**
 *
 * @author Guilherme
 */
public class LoginUsuarioView extends javax.swing.JFrame {
    private ArrayList<Usuario> usuarios;
    /**
     * Creates new form LoginUsuarioView
     */
    public LoginUsuarioView() {
        this.usuarios = new ArrayList<Usuario>();
        initComponents();
    }

    public ArrayList<Usuario> getUsuarios() {
        return usuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfCpfCnpj = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jlCadastro = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HomeAlone Webmarket");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 10, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo3.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 48, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CPF/ CNPJ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        tfCpfCnpj.setBackground(new java.awt.Color(255, 255, 255));
        tfCpfCnpj.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfCpfCnpj.setForeground(new java.awt.Color(0, 0, 0));
        tfCpfCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfCnpjActionPerformed(evt);
            }
        });
        getContentPane().add(tfCpfCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 487, 40));

        pfSenha.setBackground(new java.awt.Color(255, 255, 255));
        pfSenha.setForeground(new java.awt.Color(0, 0, 0));
        pfSenha.setToolTipText("");
        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 487, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        btEntrar.setBackground(new java.awt.Color(95, 46, 234));
        btEntrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 487, 45));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ainda não possui uma conta?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 40));

        jlCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jlCadastro.setText("Cadastre-se aqui!");
        jlCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadastroMouseClicked(evt);
            }
        });
        getContentPane().add(jlCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCpfCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfCnpjActionPerformed

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaActionPerformed

    private void jlCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadastroMouseClicked
        CadastroUsuarioView cadastro = new CadastroUsuarioView(this);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jlCadastroMouseClicked

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        long cpfCnpj = 0;
        String cpfCnpjText = tfCpfCnpj.getText();
        String senha = pfSenha.getText();
        Usuario usuarioLogado = null;

        for (Usuario usuario : usuarios) {
            if (String.valueOf(usuario.getCpfCpnj()).equals(cpfCnpjText)
                && usuario.getSenha().equals(senha)){
                usuarioLogado = usuario;
                break;
            }
        }

        if (usuarioLogado == null){
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos!");
        } else {
            HomeAloneView homeAloneView = new HomeAloneView(usuarioLogado);
            this.setVisible(false);
            homeAloneView.setVisible(true);
        }

    }//GEN-LAST:event_btEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlCadastro;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfCpfCnpj;
    // End of variables declaration//GEN-END:variables
}
