/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Boleto;
import modelo.Compra;
import modelo.Endereco;
import modelo.MetodoPagamento;
import modelo.Telefone;
import modelo.Produto;
import modelo.Email;

/**
 *
 * @author pedro
 */
public class NovoPedidoView extends javax.swing.JFrame {

    private HomeAloneView homeAloneView;
    private ArrayList<Produto> produtosCompra;
    /**
     * Creates new form NovoPedidoView
     */
    public NovoPedidoView(HomeAloneView homeAloneView) {
        this.homeAloneView = homeAloneView;
        initComponents();
        homeAloneView.getTelefones().forEach(telefone -> {cbTelefone.addItem(telefone);});
        homeAloneView.getEnderecos().forEach(endereco -> {cbEndereco.addItem(endereco);});
        homeAloneView.getCartoes().forEach(cartao -> {cbPagamento.addItem(cartao);});
        homeAloneView.getEmails().forEach(email -> {cbEmail.addItem(email);});
        Boleto boleto = new Boleto("file.pdf", "", "", "");
        cbPagamento.addItem(boleto);
        
        atualizaComboProdutos();
        homeAloneView.setVisible(false);
        this.produtosCompra = new ArrayList<Produto>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfDataPrevisao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbPagamento = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taProdutosLista = new javax.swing.JTextArea();
        jlVoltar = new javax.swing.JLabel();
        btLimparProduto = new javax.swing.JButton();
        jlAdicionaProduto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbTelefone = new javax.swing.JComboBox<>();
        btSalvar = new javax.swing.JButton();
        btNovoProduto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbEndereco = new javax.swing.JComboBox<>();
        cbEmail = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Novo Pedido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data da Previsão:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        tfDataPrevisao.setBackground(new java.awt.Color(255, 255, 255));
        tfDataPrevisao.setForeground(new java.awt.Color(0, 0, 0));
        tfDataPrevisao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDataPrevisao.setText("dd/mm/yyyy");
        tfDataPrevisao.setToolTipText("");
        tfDataPrevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataPrevisaoActionPerformed(evt);
            }
        });
        getContentPane().add(tfDataPrevisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lista de produtos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selecione os Produtos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        cbProduto.setBackground(new java.awt.Color(255, 255, 255));
        cbProduto.setForeground(new java.awt.Color(0, 0, 0));
        cbProduto.setToolTipText("");
        getContentPane().add(cbProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 460, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Método Pagamento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        cbPagamento.setBackground(new java.awt.Color(255, 255, 255));
        cbPagamento.setForeground(new java.awt.Color(0, 0, 0));
        cbPagamento.setToolTipText("");
        getContentPane().add(cbPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 120, -1));

        taProdutosLista.setBackground(new java.awt.Color(255, 255, 255));
        taProdutosLista.setColumns(20);
        taProdutosLista.setForeground(new java.awt.Color(0, 0, 0));
        taProdutosLista.setRows(5);
        taProdutosLista.setToolTipText("");
        jScrollPane2.setViewportView(taProdutosLista);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 340, 150));

        jlVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jlVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jlVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 40));

        btLimparProduto.setBackground(new java.awt.Color(95, 46, 234));
        btLimparProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLimparProduto.setForeground(new java.awt.Color(255, 255, 255));
        btLimparProduto.setText("Limpar Lista");
        btLimparProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btLimparProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 150, 30));

        jlAdicionaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jlAdicionaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAdicionaProdutoMouseClicked(evt);
            }
        });
        getContentPane().add(jlAdicionaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefone:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        cbTelefone.setBackground(new java.awt.Color(255, 255, 255));
        cbTelefone.setForeground(new java.awt.Color(0, 0, 0));
        cbTelefone.setToolTipText("");
        getContentPane().add(cbTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 130, -1));

        btSalvar.setBackground(new java.awt.Color(95, 46, 234));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Concluir");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 510, 40));

        btNovoProduto.setBackground(new java.awt.Color(95, 46, 234));
        btNovoProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btNovoProduto.setForeground(new java.awt.Color(255, 255, 255));
        btNovoProduto.setText("Novo Produto");
        btNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btNovoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 150, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        cbEndereco.setBackground(new java.awt.Color(255, 255, 255));
        cbEndereco.setForeground(new java.awt.Color(0, 0, 0));
        cbEndereco.setToolTipText("");
        getContentPane().add(cbEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 130, -1));

        cbEmail.setBackground(new java.awt.Color(255, 255, 255));
        cbEmail.setForeground(new java.awt.Color(0, 0, 0));
        cbEmail.setToolTipText("");
        getContentPane().add(cbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDataPrevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataPrevisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataPrevisaoActionPerformed

    private void jlVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVoltarMouseClicked
        this.dispose();
        this.homeAloneView.setVisible(true);
    }//GEN-LAST:event_jlVoltarMouseClicked

    private void btLimparProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparProdutoActionPerformed
        taProdutosLista.setText("");
        this.produtosCompra.clear();
    }//GEN-LAST:event_btLimparProdutoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        ArrayList<Compra> compras = homeAloneView.getCompras();
        
        String newTelefone = ((cbTelefone.getSelectedItem() == null) ? "" : cbTelefone.getSelectedItem().toString()),
               newEndereco = ((cbEndereco.getSelectedItem() == null) ? "" : cbEndereco.getSelectedItem().toString()),
               newEmail = ((cbEmail.getSelectedItem() == null) ? "" : cbEmail.getSelectedItem().toString()),
               newPagamento = ((cbPagamento.getSelectedItem() == null) ? "" : cbPagamento.getSelectedItem().toString());
        
        Compra compra = new Compra(tfDataPrevisao.getText(), 
                                   newTelefone, 
                                   newEndereco,
                                   newEmail,
                                   newPagamento);
        compra.adicionaProduto(this.produtosCompra);
        compras.add(compra);
        this.setVisible(false);
        homeAloneView.setVisible(true);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoProdutoActionPerformed
        CadastrarProdutoView cadastrarProdutoView = new CadastrarProdutoView(this, this.homeAloneView);
        cadastrarProdutoView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btNovoProdutoActionPerformed

    private void jlAdicionaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAdicionaProdutoMouseClicked
        Produto produto = (Produto) cbProduto.getSelectedItem();
        if (produto == null){
            JOptionPane.showMessageDialog(null, "Nenhum produto selecionado!");
        } else {
            String listaProduto = taProdutosLista.getText();
            listaProduto = listaProduto + produto.imprimeProduto() + System.lineSeparator();
            taProdutosLista.setText(listaProduto);
            this.produtosCompra.add(produto);
        }
    }//GEN-LAST:event_jlAdicionaProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
   

    public void atualizaComboProdutos(){
        cbProduto.removeAllItems();
        homeAloneView.getProdutos().forEach(produto -> cbProduto.addItem(produto));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimparProduto;
    private javax.swing.JButton btNovoProduto;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<Email> cbEmail;
    private javax.swing.JComboBox<Endereco> cbEndereco;
    private javax.swing.JComboBox<MetodoPagamento> cbPagamento;
    private javax.swing.JComboBox<Produto> cbProduto;
    private javax.swing.JComboBox<Telefone> cbTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlAdicionaProduto;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JTextArea taProdutosLista;
    private javax.swing.JTextField tfDataPrevisao;
    // End of variables declaration//GEN-END:variables
}
